### ISSUE TITLE
Needs a bit more basics for people who have never setup a satellite dish before.

### ISSUE THREAD

**Issue by gmaxwell** [Blockstream/satellite#1]
Needs an "Am I covered" here is how you use the coverage map, and then use the dishpointer to see if you can find a location to mount a dish with a clear view of the sky in the right direction with no obstructions.  E.g. making it clear that nearby obstructions are not good even if technically you have line of sight.  Also pointing out that cellphone compasses are usually not very accurate. :)

**Comment by blockstreamsatellite** [comment]
Will add in the am.

**Comment by ivanahepjuk** [comment]
Nice project, I am also missing that [embed dish alignment tool] in the section "IDEAL MOUNTING LOCATION"

**Comment by blockstreamsatellite** [comment]
Updated the link for the dish alignment tool.
