### ISSUE TITLE
Is data streaming now ?

### ISSUE THREAD

**Issue by aospan** [Blockstream/satellite#16]
Hello,

I see only HDLC frame delimiter (0x7E) is transmitted now (Dec 4 2017). Speed is about 100kbit/sec.
Is this normal ? Where is blockchain blocks ? Please advice.
Thanks !

P.S.
I'm on Galaxy 18 (123W). For more info screenshot:

![hdlc](https://user-images.githubusercontent.com/8099578/33566773-0b704a24-d8ef-11e7-99bd-3a4ca674e666.png)

**Comment by blockstreamsatellite** [comment]
Everything looks good.  Do you see any data coming out of /tmp/async_rx ?

**Comment by aospan** [comment]
yes, now data is coming. I can dump it from /tmp/async_rx
Thanks a lot !
