### ISSUE TITLE
Is signal transmitting now ?

### ISSUE THREAD

**Issue by aospan** [Blockstream/satellite#18]
Hello,
I'm on Galaxy 18 (123W). Signal power is "flat", no constellation. Is signal transmitting now ?
DVB transponders works fine on the same time, so dish and lnb is ok.
Thanks !

P.S.
Is it ok to ask such questions here on github ? Please, let me know if it's better to use another communication channel (email, etc).

**Comment by blockstreamsatellite** [comment]
We are looking into this now and will update soon.

Thanks!

**Comment by blockstreamsatellite** [comment]
Everything appears to be operational.  Can you double check on your end?

**Comment by aospan** [comment]
Now it works ! thanks !

**Comment by aospan** [comment]
Again no signal ;( please check. Thanks !

**Comment by blockstreamsatellite** [comment]
We actually had to move the frequency at the last minute. We have a public announcement coming shortly.  The new frequency is 12022.85 Mhz

**Comment by aospan** [comment]
Thanks for update ! 
Should it work now on new frequency ?

**Comment by blockstreamsatellite** [comment]
Yes, if you switch to the new frequency, you should be good to go!

**Comment by aospan** [comment]
Yes, it works ! But not so good as before ... constellations looks very bad:

![constellation](https://user-images.githubusercontent.com/8099578/36507889-07a9640c-1729-11e8-83cf-7adcc97c8de9.png)

and stream is recovered with errors (as expected).
I didn't changed equipment and dish alignment. 
Is something changed on your side (other than frequency) ?

Thanks !
