### ISSUE TITLE
Readme says see wiki for instructions, but no wiki

### ISSUE THREAD

**Issue by bigreddmachine** [Blockstream/satellite#2]
There are some setup instructions in the Readme, but the Readme seems to indicate there is another place to go for full instructions. Probably just an issue because the repo is so new, but thought I'd make a note in case this was lost in the shuffle.

**Comment by blockstreamsatellite** [comment]
Thanks for noticing.  The information in the Readme was originally in the wiki, but we decided to move it all to the readme, so it was a bit redundant.  Corrected the readme.

**Comment by bigreddmachine** [comment]
Cool, I would have made the correction myself but wasn't sure if the Wiki reference was old or if it was a "coming soon" thing.
