### ISSUE TITLE
B2C2 FlexcopII/II(b)/III digital TV receiver chip (TechniSat SkyStar 2 TV PCI)

### ISSUE THREAD

**Issue by gigoplast** [Blockstream/satellite#21]
How to install Blockstream Satellite Receiver with TechniSat SkyStar 2 TV PCI in ubuntu14.04 /16.04 .
requesting support ..  appreciate your HELP

**Comment by botweb** [comment]
You can follow https://hackernoon.com/building-your-own-bitcoin-satellite-node-6061d3c93e7 and https://github.com/Blockstream/satellite.
It's not possible to let bitcoind run together with the satellite modem on a Pi together, due to the modem overhead.

**Comment by gigoplast** [comment]
i mean by my question : is there any possibilty to run blockstream with this device [TechniSat SkyStar 2 TV PCI] 
![mottagare-skystar-2](https://user-images.githubusercontent.com/11947255/48670222-4ee05c80-eb14-11e8-8234-28a79b552626.jpg)

im thankfull for replaying :+1:

**Comment by VDelport** [comment]
As botweb said, no. You'll need a satellite dish, a PLL LNB with better frequency stability than conventional TV LNBs, and an RTL SDR USB receiver to receive Blockstream Satellite. The software required is the GNU radio receiver from Blockstream. The Blockstream Satellite Signal is not a TV signal. So you can not receive it with equipment for receiving DVB-S / S2. The instructions that botweb has referred to are very good. If you understand German, you can also read our technical report on receiving Blockstream Satellite at http://blockchain.hs-mittweida.de/wordpress/wp-content/uploads/2018/04/Blockstream_Satellite_Technischer_Report.pdf.
