### ISSUE TITLE
Outside coverage map

### ISSUE THREAD

**Issue by dxtrader** [Blockstream/satellite#28]
Awesome project, was starting to see what parts I already had lying around and realized I'm located outside the coverage map.  Is it still possible to connect or will signal be too weak? Just go with a bigger dish?

Edit: just realized my coordinates yield a -2 degree elevation to any satellite at best so guess I'm just waiting for that area in the middle to eventually get covered...

**Comment by blockstreamsatellite** [comment]
@dxtrader we are closing some old issues and have realized this issue was never responded. Apologies.

What is your location?

**Comment by dxtrader** [comment]
Location is UAE and Saudi Arabia

**Comment by blockstreamsatellite** [comment]
@dxtrader apologies for not replying earlier. We don't have coverage for your location yet, but it is still in the roadmap. You can check the [coverage map in our website](https://blockstream.com/satellite/#satellite_network-coverage).
