### ISSUE TITLE
Explain how to create invoices and confirmed get paid 

### ISSUE THREAD

**Issue by somethingtodo123** [Blockstream/satellite#37]
Wondering how to create invoices and let people pay. and how to confirm the payment is confirmed through satellite?

**Comment by matthewlilley** [comment]
Satellite has an API for transactions.

https://blockstream.com/satellite-api-documentation/

However, as you mentioned invoices, I think you might be looking to generate Lightning Network invoices. That's handled by a client which adheres to the Lightning Protocol, C-Lightning, LND etc... invoices can be generated by one of those.
