### ISSUE TITLE
Can the DVB-S2-based blockstream satellite receiver with an RTL-SDR be put into operation from June 1st?

### ISSUE THREAD

**Issue by VDelport** [Blockstream/satellite#48]
If I understand that correctly, the well-functioning and inexpensive receiver version of Blockstream Satellite can unfortunately no longer be used after June 1st. Have you already published all the information we need to set up a DVB-S2 receiver with an RTL-SDR, or will more information be made available in the next four days? Please provide the information for the Antenna Pointing Guide. The URL https://github.com/Blockstream/satellite/blob/master/doc/antenna-pointing#sdr-based unfortunately leads to nothing.

**Comment by blockstreamsatellite** [comment]
@VDelport All the information to set up a DVB-S2 receiver using the RTL-SDR is already available. The link you referred to is indeed broken. The correct link is: https://github.com/Blockstream/satellite/blob/master/doc/antenna-pointing.md#sdr-based

I assume you have found the link somewhere in the docs. So we will search and fix it. Thanks for raising our attention to it.

The summary of the steps to set up the RTL-SDR based receiver is the following:
1. Install the CLI:
```
sudo pip3 install blocksat-cli
```

2. Run the config helper:
```
blocksat-cli cfg
```

3. Install the required SW:
```
blocksat-cli deps install
```

4. If you are going to use gqrx for antenna pointing, generate the config for it:

```
blocksat-cli gqrx-conf
```

And then launch gqrx from the terminal:
```
gqrx
```

Of course, if you are already pointed for the previous version, you don't need to point your antenna again. If you do need to point, check the instructions in the [antenna pointing guide](https://github.com/Blockstream/satellite/blob/master/doc/antenna-pointing.md#sdr-based).

5. Run the receiver:
```
blocksat-cli sdr
```

There are many options on the above command. You can take a look at the [SDR setup guide](https://github.com/Blockstream/satellite/blob/master/doc/sdr.md).

You can also check detailed instructions directly from the CLI, by running:
```
blocksat-cli instructions
```

Hope this helps.
