### ISSUE TITLE
What are the parameters of rtl_sdr, leandvb, and tsp in the default configuration of blocksat-cli sdr?

### ISSUE THREAD

**Issue by VDelport** [Blockstream/satellite#52]
Hello, I assume blocksat-cli sdr runs the applications rtl_sdr, leandvb, and tsp  as a pipe in that order. Would you please give me all the parameters with which the three programs are executed in the default function of blocksat-cli sdr?

**Comment by blockstreamsatellite** [comment]
@VDelport sure. Just run with `--debug` option, as follows:

```
blocksat-cli --debug sdr
```

The CLI prints out the full command that is used when executed in debug mode. It will show the piping from the `rtl_sdr` app, to `leandvb`, and finally to `tsp`, including all arguments.

**Comment by VDelport** [comment]
Thank you.
