### ISSUE TITLE
With which option or configuration can you save the transport stream in a file?

### ISSUE THREAD

**Issue by VDelport** [Blockstream/satellite#59]
At blocksat-cli usb I want to save the transport stream received for a time in a file. 
How can I configure it?

**Comment by blockstreamsatellite** [comment]
Hi @VDelport ,

You need to run with option `-r [filename]`, like so:
```
blocksat-cli usb launch -r blocksat.ts
```

FYI, all commands in the CLI have help menus, so you could check, for example:
```
blocksat-cli usb launch -h
```

Once you do capture the TS file (let's say named `blocksat.ts`), you can use TSDuck to inspect it. For example:
```
 tsdump blocksat.ts
```
or
```
 tsanalyze blocksat.ts
```

**Comment by VDelport** [comment]
Thank you.
