### ISSUE TITLE
Bitcoin Satellite fork Version 0.19

### ISSUE THREAD

**Issue by 0691tuta** [Blockstream/satellite#70]
Is there a timeline to build the satellite fork from Core version 0.20 or higher? Electrum Personal Server is not working with core 0.19 
Thanks.

**Comment by blockstreamsatellite** [comment]
Hi @0691tuta ,

Thanks for your question. It's in our roadmap to upgrade the fork to a more recent core version soon. We are currently planning on releasing an update based on Bitcoin Core 0.21, once the latter is released.
